### ISSUE TITLE
NameError: global name 'requests' is not defined

### ISSUE THREAD

**Issue by EasyNT** [wendlers/ediplug-py#9]
I got this error, tested it on smartos (Solaris) and macOS 10.13:

Traceback (most recent call last):
  File "smartplug.py", line 658, in <module>
    p = SmartPlug(options.host, (options.login, options.password))
  File "smartplug.py", line 146, in __init__
    res = requests.head(self.url)
NameError: global name 'requests' is not defined

requests is installed:

# pip list
...
...
requests (2.18.4)

Too tired to find the problem :)...

**Comment by EasyNT** [comment]
Got it, the problem lies in line 146:

146         res = requests.head(self.url)

should be:

146         res = req.head(self.url)

as you did:

 26 import requests as req
